friends = ['John', 'Michael', 'Terry', 'Eric', 'Graham']
print("Lists: ", friends)
print(friends[0])
print(friends[1])
print(friends[2])
print(friends[3])
print(friends[4])
print(friends[2:4])
print(friends[:4])
print(friends[:])
print(len(friends))
print(friends.index('Eric'))
print(friends.count('Eric'))